name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Docker image
      run: docker build . -t uilianries/gcc10-xenial
    - name: Inspect Docker image
      run: docker inspect uilianries/gcc10-xenial
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - name: Docker login
      run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
    - name: Docker Upload
      run: docker upload uilianries/gcc10-xenial
