name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Base Docker image
      run: docker build Dockerfile.base -t uilianries/docker-builder-base
    - name: Inspect Docker image
      run: docker inspect uilianries/docker-builder-base
    - name: Build GCC 10 Docker image
      run: docker build Dockerfile.gcc10 -t uilianries/gcc10
    - name: Inspect Docker image
      run: docker inspect uilianries/gcc10
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - name: Docker login
      run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
    - name: Docker Upload
      run: docker upload uilianries/gcc10
