name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc10, gcc9, gcc8, clang10, clang9]
    steps:
    - uses: actions/checkout@master
    - name: Build Docker image uilianries/${{ matrix.compiler }}
      run: docker build ${{ matrix.compiler }} -t uilianries/${{ matrix.compiler }}
    - name: Inspect Docker image ${{ matrix.compiler }}
      run: docker inspect uilianries/${{ matrix.compiler }}
    - name: Test Docker Image uilianries/${{ matrix.compiler }}
      run: |
        docker run -t -d --name runner-${{ matrix.compiler }} uilianries/${{ matrix.compiler }}
        docker exec runner-${{ matrix.compiler }} conan profile new default --detect
        docker exec runner-${{ matrix.compiler }} conan install lz4/1.9.2@ -s build_type=Release --build
        docker exec runner-${{ matrix.compiler }} conan install lz4/1.9.2@ -s build_type=Debug --build
        docker exec runner-${{ matrix.compiler }} conan install gtest/1.10.0@ --build -s compiler.libcxx=libstdc++ -s build_type=Release
        docker exec runner-${{ matrix.compiler }} conan install gtest/1.10.0@ --build -s compiler.libcxx=libstdc++11 -s build_type=Release
        docker exec runner-${{ matrix.compiler }} conan install gtest/1.10.0@ --build -s compiler.libcxx=libstdc++ -s build_type=Debug
        docker exec runner-${{ matrix.compiler }} conan install gtest/1.10.0@ --build -s compiler.libcxx=libstdc++11 -s build_type=Debug
        docker stop runner-${{ matrix.compiler }}
    - name: Docker login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
    - name: Docker Upload image uilianries/${{ matrix.compiler }}
      run: docker push uilianries/${{ matrix.compiler }}
